# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Activity Stream Engagement
email: msamuel@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
  Want to know more about user engagement in Activity Stream?
  You've come to the right place! Browse some posts and learn
  things you never thought you could! :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  emtwo

# Build settings
markdown: kramdown
